# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brew:
  # Repository to push the tap to.
  github:
    owner: eriklupander
    name: homebrew-tap

  # Your app's homepage.
  # Default is empty.
  homepage: 'https://github.com/eriklupander/timesum'

  # Your app's description.
  # Default is empty.
  description: 'A simple terminal UI for calculating time worked, written in Go'

# test comment to see if goreleaser only releases on new commits